services:
  openmemory-mcp:
    image: mem0/openmemory-mcp:dev
    build:
      context: api/
      dockerfile: Dockerfile
    environment:
      - USER
      - OPENAI_API_KEY
      - MYSQL_HOST
      - MYSQL_PORT
      - MYSQL_USER
      - MYSQL_PASSWORD
      - MYSQL_DATABASE
      - QDRANT_HOST
    env_file:
      - api/.env
    ports:
      - "8765:8765"
    volumes:
      - ./api:/usr/src/openmemory
    command: >
      sh -c "uvicorn main:app --host 0.0.0.0 --port 8765 --reload --workers 4"
    networks:
      - default

  openmemory-ui:
    build:
      context: ui/
      dockerfile: Dockerfile
    image: mem0/openmemory-ui:dev
    ports:
      - "3000:3000"
    environment:
      - NEXT_PUBLIC_API_URL
      - NEXT_PUBLIC_USER_ID
    networks:
      - default

networks:
  openmemory_default:
    driver: bridge
