services:
  openmemory-mcp:
    image: dpt-openmemory-mcp:0.1.0
    build:
      context: api/
      dockerfile: Dockerfile
    environment:
      - USER
      - MYSQL_HOST
      - MYSQL_PORT
      - MYSQL_USER
      - MYSQL_PASSWORD
      - MYSQL_DATABASE
      - QDRANT_HOST
      - LLM_PROVIDER
      - LLM_MODEL
      - LLM_API_KEY
      - LLM_AZURE_DEPLOYMENT
      - LLM_AZURE_ENDPOINT
      - LLM_AZURE_API_VERSION
      - EMBEDDER_PROVIDER
      - EMBEDDER_MODEL
      - EMBEDDER_API_KEY
      - EMBEDDER_AZURE_DEPLOYMENT
      - EMBEDDER_AZURE_ENDPOINT
      - EMBEDDER_AZURE_API_VERSION

    env_file:
      - api/.env
    ports:
      - "8765:8765"
    volumes:
      - ./api:/usr/src/openmemory
    command: >
      sh -c "uvicorn main:app --host 0.0.0.0 --port 8765 --reload --workers 4"
    networks:
      - default

  openmemory-ui:
    build:
      context: ui/
      dockerfile: Dockerfile
    image: dpt-openmemory-ui:0.1.0
    ports:
      - "3000:3000"
    environment:
      - NEXT_PUBLIC_API_URL
      - NEXT_PUBLIC_USER_ID
    networks:
      - default

networks:
  openmemory_default:
    driver: bridge
